export const DEFAULT_SEARCH_LIMIT = 8
export const MAX_SEARCH_LIMIT = 25
export const DEFAULT_SEARCH_FRESHNESS_EXCLUSION_MS = 30_000
export const DEFAULT_READ_LIMIT = 12
export const MAX_READ_LIMIT = 50
export const DEFAULT_SESSION_INDEX_LIMIT = 20
export const MAX_SESSION_INDEX_LIMIT = 100
